// Code generated by mockery v2.43.2. DO NOT EDIT.

package proxy

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockTGBotSendable is an autogenerated mock type for the TGBotSendable type
type MockTGBotSendable struct {
	mock.Mock
}

type MockTGBotSendable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTGBotSendable) EXPECT() *MockTGBotSendable_Expecter {
	return &MockTGBotSendable_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: c
func (_m *MockTGBotSendable) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 tgbotapi.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) (tgbotapi.Message, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) tgbotapi.Message); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(tgbotapi.Message)
	}

	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTGBotSendable_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTGBotSendable_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - c tgbotapi.Chattable
func (_e *MockTGBotSendable_Expecter) Send(c interface{}) *MockTGBotSendable_Send_Call {
	return &MockTGBotSendable_Send_Call{Call: _e.mock.On("Send", c)}
}

func (_c *MockTGBotSendable_Send_Call) Run(run func(c tgbotapi.Chattable)) *MockTGBotSendable_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *MockTGBotSendable_Send_Call) Return(_a0 tgbotapi.Message, _a1 error) *MockTGBotSendable_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTGBotSendable_Send_Call) RunAndReturn(run func(tgbotapi.Chattable) (tgbotapi.Message, error)) *MockTGBotSendable_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTGBotSendable creates a new instance of MockTGBotSendable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTGBotSendable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTGBotSendable {
	mock := &MockTGBotSendable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
