// Code generated by "stringer -type=TextData"; DO NOT EDIT.

package tgapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TextDataText-0]
	_ = x[TextDataAnimation-1]
	_ = x[TextDataAudio-2]
	_ = x[TextDataDocument-3]
	_ = x[TextDataPhoto-4]
	_ = x[TextDataSticker-5]
	_ = x[TextDataVideo-6]
	_ = x[TextDataVoice-7]
}

const _TextData_name = "TextDataTextTextDataAnimationTextDataAudioTextDataDocumentTextDataPhotoTextDataStickerTextDataVideoTextDataVoice"

var _TextData_index = [...]uint8{0, 12, 29, 42, 58, 71, 86, 99, 112}

func (i TextData) String() string {
	if i < 0 || i >= TextData(len(_TextData_index)-1) {
		return "TextData(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextData_name[_TextData_index[i]:_TextData_index[i+1]]
}
