// Code generated by mockery v2.43.2. DO NOT EDIT.

package notifications

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHookRegistrar is an autogenerated mock type for the HookRegistrar type
type MockHookRegistrar struct {
	mock.Mock
}

type MockHookRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookRegistrar) EXPECT() *MockHookRegistrar_Expecter {
	return &MockHookRegistrar_Expecter{mock: &_m.Mock}
}

// Fire provides a mock function with given fields: ctx, msg
func (_m *MockHookRegistrar) Fire(ctx context.Context, msg Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Fire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHookRegistrar_Fire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fire'
type MockHookRegistrar_Fire_Call struct {
	*mock.Call
}

// Fire is a helper method to define mock.On call
//   - ctx context.Context
//   - msg Message
func (_e *MockHookRegistrar_Expecter) Fire(ctx interface{}, msg interface{}) *MockHookRegistrar_Fire_Call {
	return &MockHookRegistrar_Fire_Call{Call: _e.mock.On("Fire", ctx, msg)}
}

func (_c *MockHookRegistrar_Fire_Call) Run(run func(ctx context.Context, msg Message)) *MockHookRegistrar_Fire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Message))
	})
	return _c
}

func (_c *MockHookRegistrar_Fire_Call) Return(_a0 error) *MockHookRegistrar_Fire_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookRegistrar_Fire_Call) RunAndReturn(run func(context.Context, Message) error) *MockHookRegistrar_Fire_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: topicPattern, hook
func (_m *MockHookRegistrar) Register(topicPattern string, hook Hook) {
	_m.Called(topicPattern, hook)
}

// MockHookRegistrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHookRegistrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - topicPattern string
//   - hook Hook
func (_e *MockHookRegistrar_Expecter) Register(topicPattern interface{}, hook interface{}) *MockHookRegistrar_Register_Call {
	return &MockHookRegistrar_Register_Call{Call: _e.mock.On("Register", topicPattern, hook)}
}

func (_c *MockHookRegistrar_Register_Call) Run(run func(topicPattern string, hook Hook)) *MockHookRegistrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(Hook))
	})
	return _c
}

func (_c *MockHookRegistrar_Register_Call) Return() *MockHookRegistrar_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookRegistrar_Register_Call) RunAndReturn(run func(string, Hook)) *MockHookRegistrar_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookRegistrar creates a new instance of MockHookRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookRegistrar {
	mock := &MockHookRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
