name: Docker Build and Push on Master and New Tags

on:
  push:
    branches: [master]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.ref_name }}
          platforms: linux/amd64
          cache-from: type=local
          cache-to: type=local

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        run: docker buildx build --push --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest .
